version: '3'

services:
  consumer:
    build:
      context: .
      dockerfile: "./src/consumer/infra/Dockerfile"

  backend:
    build:
      context: .
      dockerfile: "./src/service/infra/Dockerfile"
    ports:
      - "5000:5000"

  rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia'

networks:
  default:
    driver: bridge
